<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCDFMXtv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCDFMXtv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCDFMXtv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCDFMXtv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCDFMXtv\App_KernelDevDebugContainer([
    'container.build_hash' => 'CDFMXtv',
    'container.build_id' => '745b4d04',
    'container.build_time' => 1604050839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCDFMXtv');
